/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "zod/v4";

export const counterResponseSchema = z.object({
    "count": z.optional(z.number()),
"timestamp": z.optional(z.string().datetime())
    })