/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { counterResponseSchema } from "./counterResponseSchema.js";
import { updateCounterSchema } from "./updateCounterSchema.js";
import { z } from "zod/v4";

/**
 * @description Counter decremented
 */
export const decrementCounter200Schema = z.lazy(() => counterResponseSchema)

export const decrementCounterMutationRequestSchema = z.lazy(() => updateCounterSchema)

export const decrementCounterMutationResponseSchema = z.lazy(() => decrementCounter200Schema)
