/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { counterResponseSchema } from "./counterResponseSchema.js";
import { z } from "zod/v4";

/**
 * @description Current counter value
 */
export const getCounter200Schema = z.lazy(() => counterResponseSchema)

export const getCounterQueryResponseSchema = z.lazy(() => getCounter200Schema)
