/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { counterResponseSchema } from "./counterResponseSchema.js";
import { updateCounterSchema } from "./updateCounterSchema.js";
import { z } from "zod/v4";

/**
 * @description Counter incremented
 */
export const incrementCounter200Schema = z.lazy(() => counterResponseSchema)

export const incrementCounterMutationRequestSchema = z.lazy(() => updateCounterSchema)

export const incrementCounterMutationResponseSchema = z.lazy(() => incrementCounter200Schema)
