/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { counterResponseSchema } from "./counterResponseSchema.js";
import { z } from "zod/v4";

/**
 * @description Counter reset
 */
export const resetCounter200Schema = z.lazy(() => counterResponseSchema)

export const resetCounterMutationResponseSchema = z.lazy(() => resetCounter200Schema)
