/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { DecrementCounterMutationRequest, DecrementCounterMutationResponse } from "../types/DecrementCounter.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const decrementCounterMutationKey = () => [{ url: '/counter/decrement' }] as const

export type DecrementCounterMutationKey = ReturnType<typeof decrementCounterMutationKey>

/**
 * {@link /counter/decrement}
 */
export async function decrementCounter(data?: DecrementCounterMutationRequest, config: Partial<RequestConfig<DecrementCounterMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<DecrementCounterMutationResponse, ResponseErrorConfig<Error>, DecrementCounterMutationRequest>({ method : "POST", url : `/counter/decrement`, data : requestData, ... requestConfig })  
  return res.data
}

export function decrementCounterMutationOptions(config: Partial<RequestConfig<DecrementCounterMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = decrementCounterMutationKey()
  return mutationOptions<DecrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: DecrementCounterMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return decrementCounter(data, config)
    },
  })
}

/**
 * {@link /counter/decrement}
 */
export function useDecrementCounter<TContext>(options: 
{
  mutation?: UseMutationOptions<DecrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: DecrementCounterMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<DecrementCounterMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? decrementCounterMutationKey()

  const baseOptions = decrementCounterMutationOptions(config) as UseMutationOptions<DecrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: DecrementCounterMutationRequest}, TContext>

  return useMutation<DecrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: DecrementCounterMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<DecrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: DecrementCounterMutationRequest}, TContext>
}