/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { GetCounterQueryResponse } from "../types/GetCounter.ts";
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from "@tanstack/react-query";
import { queryOptions, useSuspenseQuery } from "@tanstack/react-query";

export const getCounterSuspenseQueryKey = () => [{ url: '/counter' }] as const

export type GetCounterSuspenseQueryKey = ReturnType<typeof getCounterSuspenseQueryKey>

/**
 * {@link /counter}
 */
export async function getCounterSuspense(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCounterQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/counter`, ... requestConfig })  
  return res.data
}

export function getCounterSuspenseQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getCounterSuspenseQueryKey()
  return queryOptions<GetCounterQueryResponse, ResponseErrorConfig<Error>, GetCounterQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getCounterSuspense(config)
   },
  })
}

/**
 * {@link /counter}
 */
export function useGetCounterSuspense<TData = GetCounterQueryResponse, TQueryKey extends QueryKey = GetCounterSuspenseQueryKey>(options: 
{
  query?: Partial<UseSuspenseQueryOptions<GetCounterQueryResponse, ResponseErrorConfig<Error>, TData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getCounterSuspenseQueryKey()

  const query = useSuspenseQuery({
   ...getCounterSuspenseQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as UseSuspenseQueryOptions, queryClient) as UseSuspenseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}