/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { GetCounterQueryResponse } from "../types/GetCounter.ts";
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from "@tanstack/react-query";
import { queryOptions, useQuery } from "@tanstack/react-query";

export const getCounterQueryKey = () => [{ url: '/counter' }] as const

export type GetCounterQueryKey = ReturnType<typeof getCounterQueryKey>

/**
 * {@link /counter}
 */
export async function getCounter(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<GetCounterQueryResponse, ResponseErrorConfig<Error>, unknown>({ method : "GET", url : `/counter`, ... requestConfig })  
  return res.data
}

export function getCounterQueryOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const queryKey = getCounterQueryKey()
  return queryOptions<GetCounterQueryResponse, ResponseErrorConfig<Error>, GetCounterQueryResponse, typeof queryKey>({
 
   queryKey,
   queryFn: async ({ signal }) => {
      config.signal = signal
      return getCounter(config)
   },
  })
}

/**
 * {@link /counter}
 */
export function useGetCounter<TData = GetCounterQueryResponse, TQueryData = GetCounterQueryResponse, TQueryKey extends QueryKey = GetCounterQueryKey>(options: 
{
  query?: Partial<QueryObserverOptions<GetCounterQueryResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch }
}
 = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...queryOptions } = queryConfig
  const queryKey = queryOptions?.queryKey ?? getCounterQueryKey()

  const query = useQuery({
   ...getCounterQueryOptions(config),
   queryKey,
   ...queryOptions
  } as unknown as QueryObserverOptions, queryClient) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}