/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { IncrementCounterMutationRequest, IncrementCounterMutationResponse } from "../types/IncrementCounter.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const incrementCounterMutationKey = () => [{ url: '/counter/increment' }] as const

export type IncrementCounterMutationKey = ReturnType<typeof incrementCounterMutationKey>

/**
 * {@link /counter/increment}
 */
export async function incrementCounter(data?: IncrementCounterMutationRequest, config: Partial<RequestConfig<IncrementCounterMutationRequest>> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const requestData = data  
  
  const res = await request<IncrementCounterMutationResponse, ResponseErrorConfig<Error>, IncrementCounterMutationRequest>({ method : "POST", url : `/counter/increment`, data : requestData, ... requestConfig })  
  return res.data
}

export function incrementCounterMutationOptions(config: Partial<RequestConfig<IncrementCounterMutationRequest>> & { client?: typeof fetch } = {}) {
  const mutationKey = incrementCounterMutationKey()
  return mutationOptions<IncrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: IncrementCounterMutationRequest}, typeof mutationKey>({
    mutationKey,
    mutationFn: async({ data }) => {
      return incrementCounter(data, config)
    },
  })
}

/**
 * {@link /counter/increment}
 */
export function useIncrementCounter<TContext>(options: 
{
  mutation?: UseMutationOptions<IncrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: IncrementCounterMutationRequest}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<IncrementCounterMutationRequest>> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? incrementCounterMutationKey()

  const baseOptions = incrementCounterMutationOptions(config) as UseMutationOptions<IncrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: IncrementCounterMutationRequest}, TContext>

  return useMutation<IncrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: IncrementCounterMutationRequest}, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<IncrementCounterMutationResponse, ResponseErrorConfig<Error>, {data?: IncrementCounterMutationRequest}, TContext>
}