/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "../client";
import type { RequestConfig, ResponseErrorConfig } from "../client";
import type { ResetCounterMutationResponse } from "../types/ResetCounter.ts";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const resetCounterMutationKey = () => [{ url: '/counter/reset' }] as const

export type ResetCounterMutationKey = ReturnType<typeof resetCounterMutationKey>

/**
 * {@link /counter/reset}
 */
export async function resetCounter(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const { client: request = fetch, ...requestConfig } = config  
  
  const res = await request<ResetCounterMutationResponse, ResponseErrorConfig<Error>, unknown>({ method : "DELETE", url : `/counter/reset`, ... requestConfig })  
  return res.data
}

export function resetCounterMutationOptions(config: Partial<RequestConfig> & { client?: typeof fetch } = {}) {
  const mutationKey = resetCounterMutationKey()
  return mutationOptions<ResetCounterMutationResponse, ResponseErrorConfig<Error>, void, typeof mutationKey>({
    mutationKey,
    mutationFn: async() => {
      return resetCounter(config)
    },
  })
}

/**
 * {@link /counter/reset}
 */
export function useResetCounter<TContext>(options: 
{
  mutation?: UseMutationOptions<ResetCounterMutationResponse, ResponseErrorConfig<Error>, void, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: typeof fetch },
}
 = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions.mutationKey ?? resetCounterMutationKey()

  const baseOptions = resetCounterMutationOptions(config) as UseMutationOptions<ResetCounterMutationResponse, ResponseErrorConfig<Error>, void, TContext>

  return useMutation<ResetCounterMutationResponse, ResponseErrorConfig<Error>, void, TContext>({
    ...baseOptions,
    mutationKey,
    ...mutationOptions,
  }, queryClient) as UseMutationResult<ResetCounterMutationResponse, ResponseErrorConfig<Error>, void, TContext>
}