/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/


export type CounterResponse = {
    /**
     * @type number | undefined
    */
    count?: number;
    /**
     * @type string | undefined, date-time
    */
    timestamp?: string;
};