/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CounterResponse } from "./CounterResponse.ts";
import type { UpdateCounter } from "./UpdateCounter.ts";

/**
 * @description Counter decremented
*/
export type DecrementCounter200 = CounterResponse;

export type DecrementCounterMutationRequest = UpdateCounter;

export type DecrementCounterMutationResponse = DecrementCounter200;

export type DecrementCounterMutation = {
    Response: DecrementCounter200;
    Request: DecrementCounterMutationRequest;
    Errors: any;
};