/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CounterResponse } from "./CounterResponse.ts";

/**
 * @description Current counter value
*/
export type GetCounter200 = CounterResponse;

export type GetCounterQueryResponse = GetCounter200;

export type GetCounterQuery = {
    Response: GetCounter200;
    Errors: any;
};