/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CounterResponse } from "./CounterResponse.ts";
import type { UpdateCounter } from "./UpdateCounter.ts";

/**
 * @description Counter incremented
*/
export type IncrementCounter200 = CounterResponse;

export type IncrementCounterMutationRequest = UpdateCounter;

export type IncrementCounterMutationResponse = IncrementCounter200;

export type IncrementCounterMutation = {
    Response: IncrementCounter200;
    Request: IncrementCounterMutationRequest;
    Errors: any;
};