/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CounterResponse } from "./CounterResponse.ts";

/**
 * @description Counter reset
*/
export type ResetCounter200 = CounterResponse;

export type ResetCounterMutationResponse = ResetCounter200;

export type ResetCounterMutation = {
    Response: ResetCounter200;
    Errors: any;
};